### ISSUE TITLE
WebAccess 

### ISSUE THREAD

**Issue by johanneslosch** [fabuxorg/DiscordBot-Framework#14]
### Description

Give the devs the possible to Access Websites easy

**Comment by K-EY** [comment]
Probably could @RzR32 do it, if he want to

**Comment by johanneslosch** [comment]
@MakiTheGamer would you do this?

**Comment by MakiTheGamer** [comment]
I can try to do it, if i have questions I´ll write them

**Comment by johanneslosch** [comment]
👍

**Comment by johanneslosch** [comment]
- [ ] get search content
- [ ] give the result to another method
