### ISSUE TITLE
WriteFile StackOverflow

### ISSUE THREAD

**Issue by johanneslosch** [fabuxorg/DiscordBot-Framework#25]
### Description

If you want to create a File with the FileWriter you get a stackoverflow

### How to reproduce

Go to the latest commit in branch '17LogInFile' for the issue #17 and run Main.java

### Error Log 
 
```
https://gist.github.com/johanneslosch/5711483007f559de716a50f8f99a200b
```

### References

[Commit b8c8076e6c78f4d35fe0338294db05ff0b6924c8](https://github.com/fabuxorg/DiscordBot-Framework/commit/b8c8076e6c78f4d35fe0338294db05ff0b6924c8)

**Comment by johanneslosch** [comment]
if this issue is done @ me that i can close the #17 Issue @MakiTheGamer

**Comment by johanneslosch** [comment]
done

**Comment by MakiTheGamer** [comment]
done
