### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by johanneslosch** [fabuxorg/DiscordBot-Framework#8]
wirite a README.md and Wiki for users and devs

Checklist: https://github.com/K-EY/DiscordBot-Framework/issues/8#issuecomment-554086288

**Comment by K-EY** [comment]
This should be urged for release 1 

- [ ] #2 
- [ ] #3 
- [ ] #5 
- [ ] #6 
- [ ] #7 
- [ ] #10 
- [ ] #14
